create sequence Matri_id_Seq
INCREMENT BY  1
START WITH 1038
MAXVALUE 20000
NOCACHE
NOCYCLE;


create sequence Actividad_estudiante_id_Seq
INCREMENT BY  1
START WITH 1
MAXVALUE 20000
NOCACHE
NOCYCLE;

create sequence Tema_estudiante_id_Seq
INCREMENT BY  1
START WITH 1
MAXVALUE 20000
NOCACHE
NOCYCLE;